/*
 * PARIKSHIT STUDENT SATELLITE TEAM
 * MANIPAL INSTITUTE OF TECHNOLOGY
 * FILE: BSP_WWDG.h
 * TYPE: BOARD SUPPORT PACKAGE (HEADER)
 * MCU: STM32L431CC
 * DEVELOPING SUB-SYSTEM: ON-BOARD DATA HANDLING SUB-SYSTEM
 * DEVELOPER: KRISHNA BIRLA
 */

#ifndef TERTPCB_BSP_WWDG_H
#define TERTPCB_BSP_WWDG_H

#include "BSP_GENERAL.h"
#include "BSP_GLOBAL.h"

uint8_t WWDG_var = 0;

void CodeLifeEndDeinit();
void SystemReset();

#endif /* TERTPCB_BSP_WWDG_H */
